# baseURL = "https://www.westsussexscouts.org.uk/"
defaultContentLanguage = "en"
languageCode = "en"

title = "West Sussex Scouts"
# copyright = "Copy, _right?_ :thinking_face:"

disableKinds = ["taxonomy", "term"]
enableEmoji = true

[author]
headline = "Sorry, we're experiencing technical difficulties. Please contact us through the channels below." 
image = "img/logo.png" # path relative to static directory
name = "West Sussex Scouts" 

links = [
  {eventbrite = {href = "https://www.eventbrite.co.uk/o/west-sussex-scouts-3622177993", text = "Events and Training", icon = "eventbrite"}},
  {email = "mailto:countyoffice@westsussexscouts.org.uk"},
  {facebook = "https://en-gb.facebook.com/WSScouts"},
  {twitter = "https://twitter.com/westsussexscout"},
  {instagram = "https://www.instagram.com/wsscouts"},
]
# links = [
# { email = "mailto:hello@your_domain.com" },
# { link = "https://link-to-some-website.com/" },
# { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
# { apple = "https://www.apple.com" },
# { codepen = "https://codepen.io/username" },
# { dev = "https://dev.to/username" },
# { discord = "https://discord.gg/invitecode" },
# { dribbble = "https://dribbble.com/username" },
# { facebook = "https://facebook.com/username" },
# { flickr = "https://www.flickr.com/photos/username/" },
# { foursquare = "https://foursquare.com/username" },
# { github = "https://github.com/username" },
# { gitlab = "https://gitlab.com/username" },
# { google = "https://www.google.com/" },
# { instagram = "https://instagram.com/username" },
# { keybase = "https://keybase.io/username" },
# { kickstarter = "https://www.kickstarter.com/profile/username" },
# { lastfm = "https://lastfm.com/user/username" },
# { linkedin = "https://linkedin.com/in/username" },
# { mastodon = "https://mastodon.instance/@username" },
# { medium = "https://medium.com/username" },
# { microsoft = "https://www.microsoft.com/" },
# { patreon = "https://www.patreon.com/username" },
# { pinterest = "https://pinterest.com/username" },
# { reddit = "https://reddit.com/user/username" },
# { slack = "https://workspace.url/team/userid" },
# { snapchat = "https://snapchat.com/add/username" },
# { soundcloud = "https://soundcloud.com/username" },
# { steam = "https://steamcommunity.com/profiles/userid" },
# { telegram = "https://t.me/username" },
# { tiktok = "https://tiktok.com/@username" },
# { tumblr = "https://username.tumblr.com" },
# { twitch = "https://twitch.tv/username" },
# { twitter = "https://twitter.com/username" },
# { whatsapp = "https://wa.me/phone-number" },
# { youtube = "https://youtube.com/username" },
# ]

[module]
[module.hugoVersion]
extended = false
min = "0.86.1"
